-- MySQL Script generated by MySQL Workbench
-- 11/27/16 02:24:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca_qt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_qt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_qt` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca_qt` ;

-- -----------------------------------------------------
-- Table `biblioteca_qt`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `data_de_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` VARCHAR(2) NULL,
  `rua` VARCHAR(90) NULL,
  `bairro` VARCHAR(50) NULL,
  `num_casa` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`aluno` (
  `id_usuario` INT NULL,
  `matricula` INT NOT NULL,
  `id_curso` INT NULL,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  CONSTRAINT `fk_aluno_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `biblioteca_qt`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `biblioteca_qt`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`publicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `sub_titulo` VARCHAR(70) NOT NULL,
  `editora` VARCHAR(45) NULL,
  `midia` VARCHAR(45) NULL,
  `tipo_de_obra` VARCHAR(45) NULL,
  `volume` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`autor` (
  `id_publicacao` INT NULL,
  `nome` VARCHAR(60) NOT NULL,
  CONSTRAINT `fk_autor_id_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `biblioteca_qt`.`publicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`exemplar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_publicacao` INT NULL,
  `isbn` INT NOT NULL,
  `condicao` VARCHAR(45) NULL,
  `data_entrada` DATE NOT NULL,
  `ano_de_edicao` INT NULL,
  `cativo` TINYINT(1) NULL,
  `qtd_faciculos` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_exemplar_id_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `biblioteca_qt`.`publicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_exemplar` INT NULL,
  `id_usuario` INT NULL,
  `data_emprestimo` DATE NOT NULL,
  `data_devedevolver` DATE NOT NULL,
  `data_devolvido` DATE NOT NULL,
  `qtd_renovacao` INT NOT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emprestimo_id_exemplar`
    FOREIGN KEY (`id_exemplar`)
    REFERENCES `biblioteca_qt`.`exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `biblioteca_qt`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`autoriza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`autoriza` (
  `id_funcionario` INT NULL,
  `id_emprestimo` INT NULL,
  CONSTRAINT `fk_autoriza_id_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `biblioteca_qt`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autoriza_id_emprestimo`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `biblioteca_qt`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`genero` (
  `id_publicacao` INT NULL,
  `nome` VARCHAR(60) NOT NULL,
  CONSTRAINT `fk_genero_id_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `biblioteca_qt`.`publicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_qt`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_qt`.`professor` (
  `id_usuario` INT NULL,
  `siape` INT NOT NULL,
  CONSTRAINT `fk_id_professor_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `biblioteca_qt`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
